### ISSUE TITLE
As a user, I want the view to be optimized for tablets 

### ISSUE THREAD

**Issue by madasamys** [mcruncher/worshipsongs-android#323]
In order to fully utilize  the space.
As a user, I want the view to be optimized for tablets.

**Comment by GermanGospel** [comment]
@madasamys - Which views have to be optimized?

For Projector Operators: "[we] plan to provide support in tablet(next version) list of all songs in the favourite list next to a list of the parts of the current songs (as in OpenLP)." from #262

**Comment by cruncherapp** [comment]
@GermanGospel  We will have optimized all views.

**Comment by madasamys** [comment]
@GermanGospel We will have optimized all views

**Comment by madasamys** [comment]
Hi @GermanGospel, We supported optimized view for tablet. v3.328 is available in beta store. Can you test it and give feedback?

**Comment by GermanGospel** [comment]
Hi @madasamys, thanks for the tablet optimized views! I will install the new version on Saturday.

**Comment by madasamys** [comment]
Thanks @GermanGospel, Any feedback?
