### ISSUE TITLE
Song that is being presented should remain on present view while viewing other songs

### ISSUE THREAD

**Issue by michelleashwini** [mcruncher/worshipsongs-android#327]
Given user is presenting a song
When the user searches for the next song to be presented,
Then the song that is currently being presented should remain in present mode on primary device
And once the user returns to the presenting song, the user should be able to continue presenting that song.

Example scenario :

The 1st Verse of Aalugai Seiyyum Aaviyaanavarae song is currently being presented.
While this song is being presented, search for the next song to be presented.
Go back to Aalugai Seiyyum Aaviyaanavarae to present the chorus of the song
Observed :

I had to tap on present to present the song that was already being presented.
This was so I can select the chorus as the part to be presented
Expected :

After the 3rd Step from the Example Scenario, I should still see the song in present view on the primary device.

[#134 iOS](https://github.com/mcruncher/worshipsongs-ios/issues/134)

**Comment by GermanGospel** [comment]
https://github.com/mcruncher/worshipsongs-android/issues/262#issuecomment-278568872

swotge commented on 9 Feb
Preview next song: If I swipe the view to the next song, and go back to the first song, the currently projected song part is not selected. I have to push the 'project button' and than select the right song part. So its a bad idea to swipe to next song, as long as the current one is still going! ;-)
So you don't need swipe option when project song?.
The 'swipe to next song' feature is great, but it is 'broken' for the use case 'get a sneak peek at the next song while the current is still playing'. I want to sneak peek the next song and go back and finish the song without the need to push the 'sent to projector' button again.
@GermanGospel I will discus with our team and i will back.

**Comment by madasamys** [comment]
@GermanGospel This feature is requested by you, when we were working on #262. We will provide this feature later version.

**Comment by GermanGospel** [comment]
@madasamys - Yes, I copied the comment to this issue since the requested feature @michelleashwini described, sounds the same to me.

**Comment by VigneshPalanisamy** [comment]
This feature is available in beta channel. Please test and give feedback.

**Comment by GermanGospel** [comment]
@VigneshPalanisamy - Thanks for this feature! :) I only checked it in 'Song Book/Titles' view. Nice idea to highlight the 'running' song in blue colour!

I will check the behaviour in 'Favourites' view later.
