### ISSUE TITLE
As a user, I want to search by a song's title or content

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#334]
In order for the search to be efficient and relevant
As a user
I want to search by a song's title or content

NOTE: Currently, the app supports only search by content.

**Comment by madasamys** [comment]
@GermanGospel can you test this issue and give feedback? v2.256 is published to beta store.

**Comment by GermanGospel** [comment]
@madasamys - My first impressions: The two search modes are working! 👍 

But...
1. If I enter "worship" (default: 'Search by Title') and switch to 'Search by Content' the list is not updated. I need to add a character and delete it to get the list of songs with 'worship' in their content.
2. The button to switch between the mode is to far away of the text entry box. It looks disconnected and a little bit higher in position.

**Comment by madasamys** [comment]
> The button to switch between the mode is to far away from the text entry box. It looks disconnected and a little bit higher in position. 

@GermanGospel we identified this is our development environment. If reduce the space between icon and search text, It reflects on other action menu.

**Comment by sskjames** [comment]
Hi @madasamys, tested this and it works as expected.
