### ISSUE TITLE
As a user, I want the songs to be grouped by OpenLP topics

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#336]
In order to improve user experience
As a user
I want the songs to be grouped by OpenLP topics under a tab named "Categories"

Ref: The default db that's shipped with the app now has [support](https://github.com/mcruncher/worshipsongs-db-dev/issues/164) for [few](https://github.com/mcruncher/worshipsongs-db-dev/issues/165) [topics](https://github.com/mcruncher/worshipsongs-db-dev/issues/166).

**Comment by sskjames** [comment]
Scenarios:

**List songs by category**
Given the user is in the "Categories" tab
And few categories (OpenLP topics) are displayed
When the user taps a category
Then the songs that belong to that category should be listed

**Search for songs inside a category**
Given the user has tapped a category
And songs that belong to that category are listed
When the user searches for a song by title or content
Then the songs matching the search criteria under that category should be listed

**Comment by madasamys** [comment]
@GermanGospel can you test this issue?.

**Comment by sskjames** [comment]
Hi @madasamys, I've tested this and it works great. However, as highlighted by you, there is an apparent slowness when I try to view a song from a category that has a lot of songs.

**Comment by madasamys** [comment]
> However, as highlighted by you, there is an apparent slowness when I try to view a song from a category that has a lot of songs

@sskjames  can you create issue for this?
