### ISSUE TITLE
Easy to use songs db update

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#405]
In order to view the newly added songs even when there are no app updates
As a user
I want to update the songs db 

NOTE: Though the existing import database feature can be used to update the songs db, it's too technical for most of our user base.

Scenarios

**Update songs db if user confirms the update action**
Given an update is available to the songs db
When the user touches the "Update song database" menu from the app's drawer
And confirms the action
Then the latest songs db configured in the settings should be downloaded and updated
And the user should see a progress of the download

**Do not update songs db if user does not confirm the update action**
Given an update is available to the songs db
When the user touches the "Update song database" menu from the app's drawer
And does not confirm the action
Then the songs database should not be updated

**Cancel songs db update**
Given the user has initiated a songs db update
When the user cancels the action
Then the update should be cancelled

**Display a message when no updates are available**
Given there are no updates available to the songs db
When the user touches the "Update song database" menu
Then the message "No updates were found!" should be displayed

**Display a message when there is no internet connection**
Given there is no internet connection
When the user touches the "Update song database" menu
Then the message "Internet connection is needed to update the song database" should be displayed

**Comment by madasamys** [comment]
Use below REST API url to get latest commit on repository

[Latest commit from worshipsongs-android in master barnch](https://api.github.com/repos/mcruncher/worshipsongs-android/git/refs/heads/master)

Response like below
```
{
    "ref": "refs/heads/master",
    "url": "https://api.github.com/repos/mcruncher/worshipsongs-android/git/refs/heads/master",
    "object": {
        "sha": "f97351bdf788115c8cf4af4a60ef95fc7108f176",
        "type": "commit",
        "url": "https://api.github.com/repos/mcruncher/worshipsongs-
        android/git/commits/f97351bdf788115c8cf4af4a60ef95fc7108f176"
    }
}
```
