### ISSUE TITLE
Group songs by Song books

### ISSUE THREAD

**Issue by madasamys** [mcruncher/worshipsongs-android#436]
In order to search and view songs by song numbers in physical song books
As a user
I can view songs grouped by song books

**Acceptance Criteria (Scenarios)**:

**List songs by _song books_**
Given the user is in the _song books_ tab
And few _song books_ are available
When the user taps a song book
Then the songs that belong to that song book should be listed
And the songs should be sorted by song number in ascending order
And the song number should be displayed along with the song title

**Search for songs inside a _song books_**
Given the user is inside a _song book_
When the user searches for a song by song number or title or content
Then the songs in the song book that match the search criteria should be listed

**Display song in a song book**
Given the user is in a Song Book
When the user taps a song to view it
Then the song lyrics should be displayed
And the song number should be displayed along with the title

**Comment by madasamys** [comment]
TODO:

 Add song number while viewing song

**Comment by sskjames** [comment]
Updated Scenario 1 to display song number while listing songs.
Added a new scenario to display song number while viewing a song.
