### ISSUE TITLE
Upgrade SDK to v26

### ISSUE THREAD

**Issue by madasamys** [mcruncher/worshipsongs-android#502]
Google will require app updates or new app target Android 8.0 (SDK26)

Reference
[All app updates on the Play Store must now target Android 8.0+](https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/amp/) 
[Meet Google Play's target API level requirement](https://developer.android.com/distribute/best-practices/develop/target-sdk)

**Comment by sskjames** [comment]
Fonts look slightly bigger in the app interface and observed some extra spacing in lists.
