### ISSUE TITLE
Some users reported that the app displays a blank screen

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#542]
One of our users reported this via email:
```
Hi,

I would like to inform there is some problem with this app.I am unable to see any songs.it shows a blank page.i tried to uninstall & install again.it is still not working.

Priscilla Jeevamalar(Ms)
```
The user also shared a screenshot explaining the problem.
<img src="https://user-images.githubusercontent.com/229993/87262126-57f11f00-c4eb-11ea-8052-8a082df376c2.jpg" height="30%" width="30%">

The user is using Android 9.

**Comment by sskjames** [comment]
Another user also reported a similar problem:
```
Worship songs not working. It coming blank.
From 
India 
```

**Comment by madasamys** [comment]
Application store tab settings configuration values in preferences. This preference values are removed automatically on some android devices (v9.0) while updating to latest version.

_Workaround to solve this issue._
1. Go to Settings -> Tab on '**Change tab settings**' 
2. Tap on **OK** button.

**Comment by VigneshPalanisamy** [comment]
Yes Maddy, that workaround works. that was the problem...
