### ISSUE TITLE
Display songbook below each song in complete and favorite list view.

### ISSUE THREAD

**Issue by rafaeljohansen** [mcruncher/worshipsongs-android#548]
### Story
As a Worship Leader, I want the songbook to be displayed below each song in complete (titles tab) and favorite list view
So that I can prepare for the service along with other members in the worship team 

### Conditions of Acceptance
- This feature should be controlled via settings (e.g Display songbook below songs)
- By default this feature should be turned off (at least at this point of time), as this would be required only by a subset of users
- The app should leverage the features available in OpenLP 3.0

### Background
As mentioned in #221, we need an option to **display the key** of songs in the list views (both complete list and favorite list).
Because OpenLP 2.4 don't support keys and chords yet, keys can temporarily be assigned using songbooks that are given the names "Key of E", "Key of A" etc. 
However, OpenLP 3.0 (which currently is in the beta stage) does support keys and chords. Therefore, it would be wise to take a look at how this information is stored in OpenLP 3.0 and already add support for this. 
The final solution could be to add two options in the settings of your app.
- "Display songbook below songs"
- "Display key below songs"

Then we could temporarily use the "Display songbook" option until OpenLP 3.0 (with key support) has an official release. 
(The "Display songbook" option could anyway be quite useful for several reasons)

A similar feature we use in "[Worship leader](https://songs.worshipleaderapp.com)" is there called "[Show key, time signature and tempo in song list](https://songs.worshipleaderapp.com/#page-settings)".

_Ref #221:_
> @sskjames: "The app does support defining the key for a song via defining a property in "Theme, Copyrights & Comments" section of a song in OpenLP. But the key is displayed only in the presentation view of the app, I think. It should be quite easy to display it below the song. Can you please create a new issue for this?"

**Comment by pitchumani1989** [comment]
- In this issue we will work on to **Display songbook below each song in complete and favorite list view.**
- We have created separate issue [To display key below each song](https://github.com/mcruncher/worshipsongs-android/issues/557)

**Comment by pitchumani1989** [comment]
Shown songbook below songs in titles list view

![Screenshot_1622183287](https://user-images.githubusercontent.com/8839835/119940563-f716ec00-bfc1-11eb-86e5-e403568ea94f.png)

**Comment by pitchumani1989** [comment]
![Screenshot_1622183287](https://user-images.githubusercontent.com/8839835/119940816-5412a200-bfc2-11eb-9268-db7f8dbb20c2.png)

**Comment by sskjames** [comment]
Looks good @pitchumani1989. Hi @rafaeljohansen, any feedback?

**Comment by pitchumani1989** [comment]
Added a setting to turn on/off this behaviour
![Screenshot_1622189717_1](https://user-images.githubusercontent.com/8839835/119953664-cf7b5000-bfd0-11eb-947b-243c910a0f63.png)

**Comment by pitchumani1989** [comment]
Added a setting to turn on/off this behaviour 

![Screenshot_1622190368_1](https://user-images.githubusercontent.com/8839835/119954316-706a0b00-bfd1-11eb-85e6-ea9966455369.png)

**Comment by sskjames** [comment]
Tested and observed the following:

- Song book names are displayed below Songs in all the tabs including Favourites.
- Song book names are displayed only in English even if it has an associated i18n text.
- App crashes when trying to view an existing Favourite.

**Comment by sskjames** [comment]
The text "bar" is displayed when we drag and drop a song in the favourite.

**Comment by sskjames** [comment]
Song book names are not displayed for songs in existing favourites. Need to fix this as well.

**Comment by sskjames** [comment]
Merged the changes. Triggered a build. Once the build is successful, will make this build available for open beta testing.

**Comment by sskjames** [comment]
Tested the beta build 3.5.0.450 in a phone running Android 11 and found that everything works as expected.
Will proceed to release v3.5.0.
