### ISSUE TITLE
Create Live-share favourite lists from OpenLP Service files (OSZL) defined in a Dropbox folder

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#558]
### Story

As a Worship Leader, I want the app to create Live-share favourite lists from the OpenLP service files (OSZL) in a configured Dropbox folder
So that the worship team members can view the songs from the respective service files in the app

### Conditions of Acceptance
- The Dropbox folder should be configured in the app
- The Dropbox folder should be publicly accessible
- Whenever the user navigates to "Live-share Favourites" tab, the app should fetch the changes to OSZL files and create/update respective favourite lists
- When the user taps a Live-share favourite list, respective songs should be listed
- When the user taps a song inside a Live-share favourite list, respective lyrics should be displayed in the correct order
- Lyrics of a song should be displayed irrespective of whether the song is present in the songs db of the app or not

**Comment by madasamys** [comment]
Hi @sskjames , @VigneshPalanisamy , @pitchumani1989 I almost completed this feature. 

**How to configure live share path ?**

- Create dropbox folder and put into service file
- Generate share link (for ex: https://www.dropbox.com/sh/jtfbn7recw6yz9t/AACT6Bm9TDkSIWJFtmhRDmB1a?dl=0)
- Replace 0 with 1 on dropbox generated link.
- Go to App Settings
- Advanced > LiveSharePath > Paste the link 
- Tap ok

**How to view live share services?**
- Go to Live share tab and Pull down to fetch all services.
- Respective service should be displayed.

Kindly take note:
I ignored third conditions of acceptance. It may be annoying to user.
I couldn't able to run  tests on my environment. Please check this.

**Comment by sskjames** [comment]
> Hi @sskjames , @VigneshPalanisamy , @pitchumani1989 I almost completed this feature.
> 
> **How to configure live share path ?**
> 
>     * Create dropbox folder and put into service file
> 
>     * Generate share link (for ex: https://www.dropbox.com/sh/jtfbn7recw6yz9t/AACT6Bm9TDkSIWJFtmhRDmB1a?dl=0)
> 
>     * Replace 0 with 1 on dropbox generated link.
> 
>     * Go to App Settings
> 
>     * Advanced > LiveSharePath > Paste the link
> 
>     * Tap ok
> 
> 
> **How to view live share services?**
> 
>     * Go to Live share tab and Pull down to fetch all services.
> 
>     * Respective service should be displayed.
> 
> 
> **Kindly take note**:
> I ignored third conditions of acceptance. It may be annoying to user.
> I couldn't able to run spock tests on my environment. Please check this.
> This feature only work on Phone not Tablet.
> 
> **Question**
> Shall we create new issue for tablet support ?

Thanks Maddy. Testing this.

**Comment by sskjames** [comment]
Hi @madasamys, I followed the steps you mentioned:

* Created a folder in Dropbox. 
* Stored a OpenLP service file (OSZL) in the folder.
* Created a link for that folder that can be shared. Though, this means anyone with the link can only view the contents of this folder. But that's enough to test this story, I believe.
* Configured the link in the app settings. Changed the "0" at the end of the url to "1" as suggested.
* Navigated to the Live Share tab and pulled down to refresh.

However, I couldn't view the service/songs in the Live Share tab. Only the help text was displayed. Please let me  know if I missed anything.

P.S
I tried even creating a shared folder with specific Dropbox users and got the link and configured it. That didn't work either.

**Comment by sskjames** [comment]
I managed to test this in an Android 10 device.
Here are the steps I followed:
- Created a service in OpenLP with few songs and saved it to a folder in Dropbox.
- Shared this folder with the option "Anyone with the link can view".
- Copied the shared folder link and configured it in app settings.
- Had to change the "0" at the end of the shared folder link url to "1" while configuring it in the app settings.
- When I navigated to the Live Share tab and "pulled down", a list with the same name as the OpenLP service was displayed there. (Hurray!)
- When I tapped the list name, a list of songs in the same order as the service was displayed.
- When I made changes to the service from OpenLP (changing song order, adding new songs, removing songs), it was reflected as expected in the app when I "pulled down" from the Live Share tab.
- I tried creating more service files in the same shared folder and they were reflected too.

**Comment by sskjames** [comment]
When I tried this in a device running Android 7.1, the Live Share tab displayed only the help text despite many "pull down" refresh.

**Comment by sskjames** [comment]
Hi @madasamys, can you explain here why the "0" should be changed to "1" in the dropbox shared url?
And also, if that's required, can we change this automatically as the user configures it in the app settings?

What is the minimum Android version required for this feature to work? Can we enable this feature only when a particular Android version is available?

**Comment by madasamys** [comment]
@sskjames Now our app have ability to update to "1" in the dropbox shared url.
Dropbox provided below options in shared url.
Url end with 0 - Shared files or folder webpage location
Url end with 1 - Shared files or folder downloaded as zip 

>What is the minimum Android version required for this feature to work? Can we enable this feature only when a particular Android version is available?`
I am investigating on above query.  did you get any crash in live share when test on v7.x ?

**Comment by madasamys** [comment]
@sskjames , Kindly request you to publish this changes to Play store

**Comment by pixel2user** [comment]
@madasamys - Thank you very much for adding this useful feature to the app! :-)

But I was supprised that this feature is hidden behind a name that no one without knowledge of the discussions here at GitHub would understand.

It should be made clear to every user, which files are supposed to be available at the shared Dropbox folder!

Live share path
"Create favourite lists from the OpenLP service files (OSZL) located in a shared Dropbox folder"

**Comment by sskjames** [comment]
Hi @pixel2user, thank you very much for the Pull Request.
