### ISSUE TITLE
Unable to play YouTube videos in Android 11

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#561]
### What was the activity?
Tried playing a video associated with a song in a phone which runs Android 11.

### What was observed?
Got the message, "This app won't run without YouTube app. Please install YouTube app in your phone". 
Actually, the phone already had YouTube installed. I even made sure that the YouTube app is the latest version. But still got the same message.

### What is expected?
WorshipSongs app should play videos within the app just as before.

**Comment by melissadarsh** [comment]
I did not encounter any problems playing a video and was able to play them in-app or through the YouTube app. Unfortunately, I don't have the latest Android version. Tested this on Android v8.1.

**Comment by VigneshPalanisamy** [comment]
https://stackoverflow.com/questions/63909770/why-youtube-player-api-does-not-work-on-android-11

**Comment by VigneshPalanisamy** [comment]
https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error

**Comment by sskjames** [comment]
Thanks a lot Vicky for identifying the root cause of this problem.

**Comment by sskjames** [comment]
Tested this on a phone running Android 11 and the videos can be played now.
Tested also on Android 7.0 to ensure that there are no surprises.
