### ISSUE TITLE
Unit tests in Android Studio doesn't recognize source classes

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#584]
![android-studio-unit-tests-does-not-recognize-source-classes](https://user-images.githubusercontent.com/229993/193769300-bc7ce1d5-07e3-403a-9418-837565d1f42e.jpg)

**Comment by sskjames** [comment]
There were suggestions to completely uninstall Android Studio including it's cache's, preferences etc. Did that by following this [guide](https://www.geeksforgeeks.org/how-to-completely-uninstall-android-studio-on-mac/). However, the problem still remains.

**Comment by sskjames** [comment]
Created a new Android project and wrote a simple unit test for a source class. Didn't face any problem there.

**Comment by madasamys** [comment]
@sskjames , The issue happened only on groovy test class or both java test class ?. 
App using roboelectric test framework to write acceptance tests. Please check this library compatible with defined min and max sdk version.

**Comment by sskjames** [comment]
Hi @madasamys, we are forced to move way from groovy tests as the [Groovy Android Gradle Plugin](https://github.com/groovy/groovy-android-gradle-plugin) has been deprecated.

**Comment by sskjames** [comment]
This has been resolved by #589 and #591.
